// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/ShootDisk.h"
#include "Commands/ShooterAimHeight.h"
#include "Commands/ShooterSpinUp.h"
#include "Commands/ShooterStop.h"
#include "Commands/TeleopDrive.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driveJoystickLeft = new Joystick(2);
	
	diskShooter2 = new JoystickButton(driveJoystickLeft, 1);
	diskShooter2->WhenPressed(new ShootDisk());
	driveJoystickRight = new Joystick(1);
	
	diskShooter1 = new JoystickButton(driveJoystickRight, 1);
	diskShooter1->WhenPressed(new ShootDisk());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
	SmartDashboard::PutData("Teleop Drive", new TeleopDrive());
	SmartDashboard::PutData("Shoot Disk", new ShootDisk());
	SmartDashboard::PutData("Shooter Spin Up", new ShooterSpinUp());
	SmartDashboard::PutData("Shooter Stop", new ShooterStop());
	SmartDashboard::PutData("Shooter Aim Height", new ShooterAimHeight());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getDriveJoystickLeft() {
	return driveJoystickLeft;
}
Joystick* OI::getDriveJoystickRight() {
	return driveJoystickRight;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
