// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef SHOOTER_H
#define SHOOTER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "Math.h"
#define SHOOTER_P						0.0005f
#define SHOOTER_I						0.00005f
#define SHOOTER_D						0.0f
#define SHOOTER_THRESHOLD				1.0f
/**
 *
 *
 * @author ExampleAuthor
 */
class Shooter: public PIDSubsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* shooterTalon1;
	GearTooth* shooterEncoder;
	SpeedController* shooterTalon2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Timer *shooterTime;
	int previousCount;
	
	Shooter();
	void InitDefaultCommand();
	void SetWheelSpeed(float speed);
	double ReturnPIDInput();
	void UsePIDOutput(double);
	void SetSpeed(double speed);
	bool AtSetpoint();
	void Stop();
	double GetRPM();
	void SetPID(float p, float i, float d);
	float GetP();
	float GetI();
	float GetD();
	double prevValue;
	
};
#endif
